add completion dialog and option
umd-annotation/umd-annotation-tool pull request #78
Opened 2023-02-21 20:42 UTC by BryonLewis

resolves #77 

Image is shown on completion of loading:
![image](https://user-images.githubusercontent.com/61746913/220453646-f25f9f1a-5e78-416f-ae39-74fbf873f1ea.png)

On dismissal, you get this screen, or after the last submit action:
![image](https://user-images.githubusercontent.com/61746913/220453711-a65e9265-d7b6-4929-9049-3a295f3dc57b.png)

2023-02-22 15:21 UTC, waxlamp requested changes
I've strengthened and explicitized the language to provide more of a warning feeling. Together with making the dialog a warning dialog, this should bring enough awareness to annotators to prevent issues.

2023-02-22 15:21 UTC, waxlamp commented on client/src/components/UMDAnnotation.vue
> +          title: 'Data already annotated',
```suggestion
          title: 'Video already annotated!',
```

2023-02-22 15:21 UTC, waxlamp commented on client/src/components/UMDAnnotation.vue
> +        const text = 'This Video has already been annotated.  Click OK to review annotations.';
```suggestion
        const text = 'This video has already been fully annotated. You can choose to edit or re-do these annotations, but you should do so with caution, and generally only if you have been instructed to.';
```

2023-02-22 15:21 UTC, waxlamp commented on client/src/components/UMDAnnotation.vue
> +          positiveButton: 'OK',
```suggestion
          positiveButton: 'Edit anyway',
```

2023-02-22 20:05 UTC, BryonLewis commented
![image](https://user-images.githubusercontent.com/61746913/220746898-8d77d664-0ad1-4822-a97d-1cf9e1af08f8.png)

2023-02-23 15:10 UTC, waxlamp approved these changes

2023-02-23 15:20 UTC, merged